name: Project tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'

      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio

      - name: Checkout
        uses: actions/checkout@master

      - name: Build Project
        run: platformio run
